services:
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: gik
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: gik-keycloak
    restart: always
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev --import-realm
    ports:
      - '8080:8080'
